import React from 'react'
import getWiki  from '../../../lib/getWiki'
import type { Metadata } from "next";
import Item from './components/Item';
type Props = {
    params:{
        searchTerm:string
    }
}
export async function generateMetadata({params:{searchTerm}}: Props): Promise<Metadata> {
    const wikiData: Promise<SearchResult> = getWiki(searchTerm);
    const data = await wikiData;  
    const displayTerm=searchTerm.replaceAll('%20','  ')

      if (!data?.query?.pages) {
      return {
        title: "undefind",
      };
    }
    return {
      title:displayTerm ,
      description: "Generated by create next app",
    };
  }
export default async function SearchTerm({params:{searchTerm}}: Props) {
    const wikiData:Promise<SearchResult>=getWiki(searchTerm)
    const data=await wikiData
    const result:Result[]|undefined=data?.query?.pages    
    const content=(
        <main className='bg-white'>
            {result?Object.values(result).map(res=><Item key={res.pageid} result={res}></Item>):<h2>{`${searchTerm}not found`}</h2>}
        </main>
    )
  return content
}