import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Bar from './components/Bar'
import MyProfilePic from './components/MyProfilePic'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "sya's blog",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        {/* <nav>
          <h1>My nav</h1>
        </nav> */}
        {/* <Navbar></Navbar> */}
        {/* <Bar></Bar>
        <MyProfilePic></MyProfilePic> */}
        {children}</body>
    </html>
  )
}
