import React from "react";
import { notFound } from "next/navigation";
import { getSortedPostData ,getPostData} from "../../../../lib/post";
import Link from "next/link";
export async function generateMetadata({
  params,
}: {
  params: { postsId: string };
}) {
  const posts = getSortedPostData();
  const { postsId } = params;
  const post = posts.find((post) => post.id === postsId);
  if(!post){
    return {
        title:'Not found'
    }
  }
  return {
    title: post?.title,
    description: "Generated by create next app",
  };
}
export default async function page({
  params,
}: {
  params: { postsId: string };
}) {
  const post = getSortedPostData();
  const { postsId } = params;
  if (!post.find((post) => post.id === postsId)) {
    return notFound();
  }
  const {title,date,contentHtml}=await getPostData(postsId)
  
  return (<div>
   <h1>{title}</h1>
   <p>{date}</p>
   <section dangerouslySetInnerHTML={{__html:contentHtml}}></section>
   <p><Link href="/">back to home</Link></p>
    </div>);
}
